INSERT INTO `role`(`id`, `name`) VALUES (1, 'PM-项目经理');
INSERT INTO `role`(`id`, `name`) VALUES (2, 'SE-软件工程师');
INSERT INTO `role`(`id`, `name`) VALUES (3, 'PG-程序员');
INSERT INTO `role`(`id`, `name`) VALUES (4, 'TL-组长');
INSERT INTO `role`(`id`, `name`) VALUES (5, 'GL-组长');
INSERT INTO `role`(`id`, `name`) VALUES (6, 'QC-品质控制');
INSERT INTO `role`(`id`, `name`) VALUES (7, 'SA-架构师');
INSERT INTO `role`(`id`, `name`) VALUES (8, 'SYSTEM-系统管理员');
INSERT INTO `role`(`id`, `name`) VALUES (9, 'HR-人事');
